services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    networks:
      - calTracker-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testDb
      MYSQL_USER: user_calTracker
      MYSQL_PASSWORD: password

  cal-app:
    build: .
    container_name: cal-app
    restart: always
    networks:
      - calTracker-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/testDb
      SPRING_DATASOURCE_USER: user_calTracker
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysqldb

networks:
  calTracker-network: